### ISSUE TITLE
TODO: Changes to flow

### ISSUE THREAD

**Issue by GYTO** [GYTO/wsc#7]
Order
- [x] - Cost Field
- [x] - Total Field
- [x] - Number of char to engrave
- [x] - Tax 0.8%
- [ ] - Invoice printing into account

- Emails to user and admin `ignore, will not do`

- [ ] Fake payment process for payment on delivery

**Comment by GYTO** [comment]
Block the user to edit the order if the status of the order is "In Progress"

**Comment by GYTO** [comment]
#6
